trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Validate
  displayName: Validate stage
  jobs:
  - job: Validate
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
    - script: echo my Terraform Validate

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Validate
  jobs:
  - deployment: Deploy
    displayName: Deploy job
    pool:
      vmImage: ubuntu-latest
    environment: 'Deploy Terraform environment' #creates an environment if it doesn't exist
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - script: echo my Terraform Deploy
      